spring:
  application:
    name: gateway-gateway
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
    loadbalancer:
      ribbon:
        enabled: false # 关闭Ribbon
    gateway:
      routes:
        - id: gateway-server
          uri: http://127.0.0.1:57468
          #uri: lb://gateway-server
          predicates:
          - Path=/gateway-server/**
          filters:
          - StripPrefix=1 #去掉Path一个/路径分割,http://127.0.0.1:57468/**

server:
  port: 6060



