spring:
  application:
    name: gateway-zuul
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
    loadbalancer:
      ribbon:
        enabled: false # 关闭Ribbon
server:
  port: 7070
zuul:
  routes:
    gateway-server:
      path: /gateway-server/**
      url: http://127.0.0.1:57468
